#!/usr/bin/env node
/**
 * Копия движка роудбука для npm-пакета.
 *
 * Развёрнутый сервер берёт движок прямо из репозитория сайта (resources/js/roadbook) —
 * правки роудбука доходят до plan_road_trip сами. В npm-пакете сайта нет, поэтому перед
 * публикацией сюда, в engine/, копируются ровно те файлы, что импортирует plan.js.
 * Структура папок та же, что в resources/js: относительные импорты движка не меняются.
 *
 *   node scripts/sync-engine.mjs [путь к resources/js]
 */
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const from = resolve(process.argv[2] ?? join(here, "../../resources/js"));
const to = resolve(here, "../engine");

const FILES = ["roadbook/plan.js", "roadbook/plan", "roadbook/rows", "visa-calc-core.js", "fuel-calc-core.js", "geo/country-at.js"];

if (!existsSync(join(from, "roadbook/plan.js"))) {
  console.error(`Roadbook engine not found in ${from}`);
  process.exit(1);
}

rmSync(to, { recursive: true, force: true });
for (const f of FILES) {
  mkdirSync(dirname(join(to, f)), { recursive: true });
  cpSync(join(from, f), join(to, f), { recursive: true });
}
writeFileSync(join(to, "package.json"), JSON.stringify({ type: "module" }, null, 2) + "\n");
writeFileSync(join(to, "README.md"), "Copy of the OpenVan roadbook plan engine (resources/js of openvan.camp), generated by scripts/sync-engine.mjs. Do not edit here.\n");
console.log(`Engine copied: ${from} → ${to}`);
